caldb_directory = 'C:/Users/swarm/Software/Bitbucket/caldb-inputdata'
reflib_directory = 'C:/Users/swarm/Software/ReflectLib'
default_det_pointer = 'C:/Users/swarm/Software/python_repository/arcusTrace/ParamFiles/Arcus_DetectorArray_Specs_Rev3p0_171211.csv'
bitbucket_path = 'C:/Users/swarm/Software/Bitbucket/caldb-inputdata'
default_xou_pointer = 'C:/Users/swarm/Software/python_repository/arcusTrace/ParamFiles/Arcus_SPO_XOU_Specs_Rev1p0_171112.csv'
default_xou_ref_pointer = 'C:/Users/swarm/Software/ReflectLib/SL_LSi02_LThick1p0_LRough0p4_SSi_SRough0p0_Pol1_CXRO.npy'
#MLMirror_L1SiC_L2Ir_SubSi_L1Thick_6p0L2Thick_10p0_Rough4p00AngRMS_X-rayRefData.npy'
default_facet_pointer = 'C:/Users/swarm/Software/python_repository/arcusTrace/ParamFiles/Arcus_CATGrating_Facets_Specs_Rev1p0_171112.csv'
default_diff_eff_pointer = 'C:/Users/swarm/Software/Bitbucket/caldb-inputdata/gratings/Si_4um_deep_30pct_dc_extended.csv'
grat_path = 'C:/Users/swarm/Software/python_repository/arcusTrace/ParamFiles/171019_GratPoints_OC13_XYZ.txt'